---
# Galaxy conf
## This is the galaxy for the french G33kTeam apps access.
cas_server: "https://accounts.esn.org/cas"
country: "FR"
## Roles for access
global_roles:
  - "IT.it_support"
  - "International.ITSupport"
  - "National.webmaster:FR"
## Write an issue and tag @@ESNFranceG33kTeam/admin to be add if your are part of the G33kTeam
geek_username:
  - "Mickahell"
## Default local conf
local_roles:
  - "Local.regularBoardMember"
  - "Local.webmaster"
  - "Local.activity"
  - "Local.boardSupport"
  - "Local.activeMember"
